### ISSUE TITLE
Incosistency after renaming the package

### ISSUE THREAD

**Issue by dsturm** [thetre97/gridsome-plugin-image-cdn#9]
Hey,

there is some incosistency after [renaming the package](https://github.com/thetre97/gridsome-plugin-cdn-images/commit/01705c30c10b3bc30cd1396c4a104287e9261c87#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). The Git-Url and registered package name at npm is still `gridsome-plugin-cdn-images` - the package name though is `gridsome-plugin-image-cdn`. This leads to an error while adding the package mentioned in the [README](https://github.com/thetre97/gridsome-plugin-cdn-images/blob/master/README.md#install).

```sh
yarn add gridsome-plugin-cdn-images
yarn add v1.21.1
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/gridsome-plugin-cdn-images: Not found".
...
```

Cheers,
Daniel

**Comment by travis-r6s** [comment]
Hello @dsturm - thanks for catching this! I have now updated the git repo and readme to reflect the actual package name.

Thanks,

Travis
